const productApi = [
  {
    id: 1,
    quantity: '800',
    type: 'g',
    defaultQty: '1',
    defaultTyp: 'kg',
    brand: '',
    image: 'https://via.placeholder.com/1000',
    tr: {
      title: 'Salkım Somates',
      currency: 'TRY',
      symbol: '₺',
      production: 'Belçika',
      category: 'Sebze',
    },
    de: {
      title: 'Strauchtomaten',
      currency: 'EUR',
      symbol: '€',
      production: 'Belgien',
      category: 'Gemüse',
    },
    en: {
      title: 'Cluster Tomatoes',
      currency: 'USD', // I'm assuming you want USD for English translations, please adjust if needed
      symbol: '$',
      production: 'Belgium',
      category: 'Vegetable',
    },
  },
  {
    id: 2,
    quantity: '2',
    type: 'l',
    defaultQty: '1',
    defaultTyp: 'l',
    brand: 'Coca Cola',
    image: 'https://via.placeholder.com/1000',
    tr: {
      title: '2lt Coca Cola',
      currency: 'TRY',
      symbol: '₺',
      production: '',
      category: 'İçecek',
    },
    de: {
      title: 'Coca Cola Zzgl. Pfand',
      currency: 'EUR',
      symbol: '€',
      production: '',
      category: 'Getränk',
    },
    en: {
      title: '2lt Coca Cola',
      currency: 'USD',
      symbol: '$',
      production: '',
      category: 'Drink',
    },
  },
  {
    id: 3,
    quantity: '1000',
    type: 'g',
    defaultQty: '1',
    defaultTyp: 'kg',
    brand: 'Golden Farm',
    image: 'https://via.placeholder.com/1000',
    tr: {
      title: 'Yeşil Biber',
      currency: 'TRY',
      symbol: '₺',
      production: 'Türkiye',
      category: 'Sebze',
    },
    de: {
      title: 'Grüne Paprika',
      currency: 'EUR',
      symbol: '€',
      production: 'Türkei',
      category: 'Gemüse',
    },
    en: {
      title: 'Green Pepper',
      currency: 'USD',
      symbol: '$',
      production: 'Turkey',
      category: 'Vegetable',
    },
  },
  {
    id: 4,
    quantity: '1',
    type: 'l',
    defaultQty: '1',
    defaultTyp: 'l',
    brand: 'Fanta',
    image: 'https://via.placeholder.com/1000',
    tr: {
      title: 'Fanta Portakal',
      currency: 'TRY',
      symbol: '₺',
      production: '',
      category: 'İçecek',
    },
    de: {
      title: 'Fanta Orange',
      currency: 'EUR',
      symbol: '€',
      production: '',
      category: 'Getränk',
    },
    en: {
      title: 'Fanta Orange',
      currency: 'USD',
      symbol: '$',
      production: '',
      category: 'Drink',
    },
  },
  {
    id: 5,
    quantity: '150',
    type: 'g',
    defaultQty: '1',
    defaultTyp: 'kg',
    brand: 'Deluxe Nuts',
    image: 'https://via.placeholder.com/1000',
    tr: {
      title: 'Badem',
      currency: 'TRY',
      symbol: '₺',
      production: 'Antep',
      category: 'Kuruyemiş',
    },
    de: {
      title: 'Mandeln',
      currency: 'EUR',
      symbol: '€',
      production: 'Antep',
      category: 'Nüsse',
    },
    en: {
      title: 'Almonds',
      currency: 'USD',
      symbol: '$',
      production: 'Antep',
      category: 'Nuts',
    },
  },
];

export default productApi;
